# Generated by Django 5.0.4 on 2024-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='projects',
            name='techused',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
