# Generated by Django 5.0.4 on 2024-12-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_projects_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='username',
        ),
    ]
