# Generated by Django 5.0.4 on 2024-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_projects_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Theme 1'), (2, 'Theme 2'), (3, 'Theme 3'), (4, 'Theme 4')], default=1),
        ),
    ]
