# Generated by Django 5.0.4 on 2024-12-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
