# Generated by Django 5.0.4 on 2025-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
