# Generated by Django 5.0.4 on 2025-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_news_alter_info_body_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='about',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
