# Generated by Django 5.0.4 on 2025-01-02 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_about_alter_education_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2001, 1, 1)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mapadd',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 16, 54, 53, 296467, tzinfo=datetime.timezone.utc)),
        ),
    ]
