# Generated by Django 5.0.4 on 2025-01-02 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 16, 59, 37, 946743, tzinfo=datetime.timezone.utc)),
        ),
    ]
