# Generated by Django 5.0.4 on 2025-01-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_news_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='timex',
        ),
    ]
